### ISSUE TITLE
Getting Started Error: <.host>: can't evaluate field host in type interface {}

### ISSUE THREAD

**Issue by HilariousGil** [Signalen/helm-charts#77]
Trying to follow the steps to get start with these Helm-Charts but I'm getting the same error in all of them.
Which relates to [this line of code](https://github.com/Signalen/helm-charts/blob/master/charts/backend/templates/ingress.yaml#L41).

It gives the error:
 "/templates/ingress.yaml" at <.host>: can't evaluate field host in type interface {}
 
Any suggestion of what I might be doing wrong, or miss some configuration?

**Comment by 4c0n** [comment]
@lennartack @bartjkdp Would you be able to help out with this?

**Comment by lennartack** [comment]
It seems the instructions in the Readme are wrong:
```
  --set "ingress.hosts[0]=dex.signalen.example.com"
```
This should be:
```
  --set "ingress.hosts[0].host=dex.signalen.example.com"
```
See the specification here: https://github.com/Signalen/helm-charts/blob/24a20fcbc3cffe0386edf605a5293d2820cc4a44/charts/backend/values.yaml#L42-L46

@HilariousGil does this work?

**Comment by bartjkdp** [comment]
Created a PR that updates the docs #78
